-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfhFBsvYP6dElusfP
ltWEy1++Eel9WnnL+pNxAgdiLKGgCgYIKoZIzj0DAQehRANCAARodJ7RpHuQA9EU
hjqSjy3eUAsmg+kW3eyjnVR5eIaqIXbcRsd7jHklWdfAmLoFdvuJaLK5WJgBzud3
CwbET494
-----END PRIVATE KEY-----